'use strict';

export const IMAGE_STATUS = {
	INITIATING: null,
	CONTOUR: 7,
	SHARDING: 6,
	CUTTING: 5,
	DECODING_BUBBLE: 4,
	DECODING_NUMBER: 3,
	ANNOTATION: 2,
	DONE: 1,			// DO NOT CHANGE
	FAILED: 0			// DO NOT CHANGE
}
